# Numpy Method
- np.array([])
- np.max()
- np.min()
- np.add()
- np.max()
- np.mod()
- np.reciprocal()
- np.divide()
- np.multiply()

In [1]:
import numpy as np

In [2]:
a = np.array([1,23,45,45])
b = np.array([23,33,44,55])
a + b

array([ 24,  56,  89, 100])

In [3]:
np.add(a,b)

array([ 24,  56,  89, 100])

In [9]:
# np.add
# np.substract()
# np.multiply()
# np.divide()
# np.mod()
# np.power()
# np.reciprocal()

In [5]:
np.add(a,b,a)

array([ 24,  56,  89, 100])

In [10]:
c = np.array([12,22,33,33])

In [11]:
np.add(a,b,c)

array([ 47,  89, 133, 155])

In [12]:
np.divide(a,b)

array([1.04347826, 1.6969697 , 2.02272727, 1.81818182])

In [13]:
np.power(a,b)

array([                  0,                   0, 7644687533790605217,
                         0])

In [14]:
a = np.array([1,2,4,4])
b = np.array([2,3,4,5])

In [15]:
np.power(a,b)

array([   1,    8,  256, 1024])

In [103]:
# astype : Change data type 

In [17]:
a.astype

<function ndarray.astype>

In [18]:
b.dtype

dtype('int64')

In [19]:
a

array([1, 2, 4, 4])

In [20]:
b

array([2, 3, 4, 5])

In [21]:
np.mod(a, b)

array([1, 2, 0, 4])

# np.reciprocal
- a = 1/a

In [26]:
a

array([1, 2, 4, 4])

In [31]:
a = a.astype('float16')

In [32]:
np.reciprocal(a)

array([1.  , 0.5 , 0.25, 0.25], dtype=float16)

In [33]:
b

array([1, 0, 0, 0])

In [38]:
b = np.array([2,3,4,5],dtype='float16')

In [39]:
np.reciprocal(b)

array([0.5   , 0.3333, 0.25  , 0.2   ], dtype=float16)

# np.arange() , np.min() , np.max(), np.argmax(), np.argmin()

In [40]:
a = np.arange(1,25,1)

In [41]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [42]:
a.ndim

1

In [44]:
a.reshape(1,24)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [46]:
a.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [47]:
a = np.arange(1,26).reshape(5,5)

In [48]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
a.ndim

2

In [50]:
a = np.arange(1,28).reshape(3,3,3)

In [51]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [52]:
a.ndim

3

In [53]:
a = np.random.randint(1,100,(5,5))

In [54]:
a

array([[78, 81, 23, 49, 43],
       [76, 41, 27, 17, 48],
       [43,  5, 16, 45, 93],
       [91, 87, 30,  4, 17],
       [ 8, 79, 59, 58, 11]], dtype=int32)

In [55]:
np.min(a)

np.int32(4)

In [56]:
np.max(a)

np.int32(93)

In [57]:
a.min()

np.int32(4)

In [58]:
a.max()

np.int32(93)

In [59]:
# np.min() and a.min() 
# np.min(a) → A NumPy function that takes the array as an argument.
# a.min() → An array method that is called directly on the array object.

In [60]:
a.max()

np.int32(93)

In [61]:
a

array([[78, 81, 23, 49, 43],
       [76, 41, 27, 17, 48],
       [43,  5, 16, 45, 93],
       [91, 87, 30,  4, 17],
       [ 8, 79, 59, 58, 11]], dtype=int32)

max(a.flatten())

In [63]:
## Cloumn or row wise max and min find ??

In [64]:
np.max(a)

np.int32(93)

In [65]:
a

array([[78, 81, 23, 49, 43],
       [76, 41, 27, 17, 48],
       [43,  5, 16, 45, 93],
       [91, 87, 30,  4, 17],
       [ 8, 79, 59, 58, 11]], dtype=int32)

In [66]:
np.max(a,axis=0)

array([91, 87, 59, 58, 93], dtype=int32)

In [67]:
# axis = 0 => Along cloumns
# axis = 1 => Along rows

In [68]:
a

array([[78, 81, 23, 49, 43],
       [76, 41, 27, 17, 48],
       [43,  5, 16, 45, 93],
       [91, 87, 30,  4, 17],
       [ 8, 79, 59, 58, 11]], dtype=int32)

In [69]:
np.max(a,axis=1)

array([81, 76, 93, 91, 79], dtype=int32)

In [70]:
np.min(a,axis=0)

array([ 8,  5, 16,  4, 11], dtype=int32)

In [71]:
np.max(a,axis=1)

array([81, 76, 93, 91, 79], dtype=int32)

# np.sum()

In [72]:
a

array([[78, 81, 23, 49, 43],
       [76, 41, 27, 17, 48],
       [43,  5, 16, 45, 93],
       [91, 87, 30,  4, 17],
       [ 8, 79, 59, 58, 11]], dtype=int32)

In [73]:
np.sum(a)

np.int64(1129)

In [74]:
np.sum(a,axis=0)

array([296, 293, 155, 173, 212])

In [75]:
np.sum(a,axis=1)

array([274, 209, 202, 229, 215])

In [76]:
a

array([[78, 81, 23, 49, 43],
       [76, 41, 27, 17, 48],
       [43,  5, 16, 45, 93],
       [91, 87, 30,  4, 17],
       [ 8, 79, 59, 58, 11]], dtype=int32)

In [77]:
a.min()

np.int32(4)

In [78]:
a.min(axis=0)

array([ 8,  5, 16,  4, 11], dtype=int32)

In [79]:
a.sum(axis=1)

array([274, 209, 202, 229, 215])

In [87]:
a = np.arange(1,28,1).reshape(3,3,3)
a = np.random.randint(1,500,(3,3,3))

In [88]:
a

array([[[ 66, 464, 332],
        [ 72, 323, 189],
        [147, 366, 371]],

       [[409, 392, 464],
        [260,  12, 312],
        [349, 429, 134]],

       [[312, 181, 310],
        [ 33, 219, 309],
        [ 97, 141,  50]]], dtype=int32)

In [89]:
a.min()

np.int32(12)

In [90]:
a.min(axis=0)

array([[ 66, 181, 310],
       [ 33,  12, 189],
       [ 97, 141,  50]], dtype=int32)

In [91]:
a.min(axis=1)

array([[ 66, 323, 189],
       [260,  12, 134],
       [ 33, 141,  50]], dtype=int32)

In [92]:
a.min(axis=2)

array([[ 66,  72, 147],
       [392,  12, 134],
       [181,  33,  50]], dtype=int32)

In [93]:
np.max(a,axis=0)

array([[409, 464, 464],
       [260, 323, 312],
       [349, 429, 371]], dtype=int32)

In [94]:
np.max(a,axis=1)

array([[147, 464, 371],
       [409, 429, 464],
       [312, 219, 310]], dtype=int32)

In [96]:
a

array([[[ 66, 464, 332],
        [ 72, 323, 189],
        [147, 366, 371]],

       [[409, 392, 464],
        [260,  12, 312],
        [349, 429, 134]],

       [[312, 181, 310],
        [ 33, 219, 309],
        [ 97, 141,  50]]], dtype=int32)

In [97]:
np.max(a,axis=0)

array([[409, 464, 464],
       [260, 323, 312],
       [349, 429, 371]], dtype=int32)

In [101]:
a

array([[[ 66, 464, 332],
        [ 72, 323, 189],
        [147, 366, 371]],

       [[409, 392, 464],
        [260,  12, 312],
        [349, 429, 134]],

       [[312, 181, 310],
        [ 33, 219, 309],
        [ 97, 141,  50]]], dtype=int32)

In [102]:
np.max(a,axis=1)

array([[147, 464, 371],
       [409, 429, 464],
       [312, 219, 310]], dtype=int32)