# Numpy Method
- np.arrgmax()
- np.argmin()
- np.nditer()
- np.ndenumerate()
- np.concatenate()
- np.stack()

In [2]:
import numpy as np

In [3]:
# np.arrgmax()
# At which index is the  maximum value

In [4]:
np.random.seed(10)
a = np.random.randint(1,10,(5,5))

In [5]:
a

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9],
       [2, 9, 5, 2, 4],
       [7, 6, 4, 7, 2]], dtype=int32)

In [6]:
np.max(a)

np.int32(9)

In [7]:
np.argmax(a)

np.int64(5)

In [8]:
np.min(a)

np.int32(1)

In [9]:
# argmin()
# At which index is minimum value

In [10]:
np.argmin(a)

np.int64(1)

In [11]:
a

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9],
       [2, 9, 5, 2, 4],
       [7, 6, 4, 7, 2]], dtype=int32)

In [12]:
np.min(a,axis=0)

array([2, 1, 2, 1, 2], dtype=int32)

In [13]:
np.argmin(a,axis=0)

array([3, 0, 0, 0, 0])

In [14]:
np.argmin(a,axis=1)

array([1, 1, 1, 0, 4])

# Iteration Array
- np.nditer()
- np.ndenumeartor()

In [15]:
a  = np.random.randint(1,100,10)

In [16]:
a

array([32, 58, 37, 28, 19, 94, 78, 23, 24, 95], dtype=int32)

In [17]:
for i in a:
    print(i)

32
58
37
28
19
94
78
23
24
95


In [18]:
a  = np.random.randint(1,100,(2,2))

In [19]:
a

array([[12, 29],
       [75, 89]], dtype=int32)

In [20]:
for i in a:
    print(i)

[12 29]
[75 89]


In [21]:
for i in a:
    for j in i:
        print(j)

12
29
75
89


In [22]:
a  = np.random.randint(1,100,(1,3,3))

In [23]:
a

array([[[10, 16, 19],
        [81, 72, 89],
        [12, 18, 47]]], dtype=int32)

In [24]:
for i in a:
    print(i)

[[10 16 19]
 [81 72 89]
 [12 18 47]]


In [25]:
for i in a:
    for j in i:
        print(j)

[10 16 19]
[81 72 89]
[12 18 47]


In [26]:
for i in a:
    for j in i:
        for k in j:
            print(k)

10
16
19
81
72
89
12
18
47


In [27]:
# np.nditer()

In [28]:
a

array([[[10, 16, 19],
        [81, 72, 89],
        [12, 18, 47]]], dtype=int32)

In [29]:
np.nditer(a)

In [30]:
list(np.nditer(a))

[array(10, dtype=int32),
 array(16, dtype=int32),
 array(19, dtype=int32),
 array(81, dtype=int32),
 array(72, dtype=int32),
 array(89, dtype=int32),
 array(12, dtype=int32),
 array(18, dtype=int32),
 array(47, dtype=int32)]

In [31]:
print(np.array(np.nditer(a)))

[10 16 19 81 72 89 12 18 47]


In [32]:
for i in np.array(np.nditer(a)):
    print(i)

10
16
19
81
72
89
12
18
47


In [33]:
for i in np.nditer(a):
    print(i)

10
16
19
81
72
89
12
18
47


In [34]:
# np.enumerate()

In [35]:
a

array([[[10, 16, 19],
        [81, 72, 89],
        [12, 18, 47]]], dtype=int32)

In [36]:
for index,value in enumerate(a):
    print(index,value)
    print("----------")

0 [[10 16 19]
 [81 72 89]
 [12 18 47]]
----------


In [37]:
a = np.random.randint(1,300,(2,5,5))

In [38]:
a

array([[[136, 204, 285, 290, 251],
        [ 45, 134,   5,  72, 183],
        [291, 272, 144, 135, 247],
        [ 86, 235, 151,  12, 113],
        [269, 221,  63, 186,  80]],

       [[233,  43, 238, 236,  46],
        [202, 166, 129,  24,   4],
        [286, 273, 113,  15,  52],
        [ 80, 244, 274, 179,  54],
        [235, 274, 234,  42,  91]]], dtype=int32)

In [39]:
for index,value in enumerate(a):
    print(index ,value)
    print("------")

0 [[136 204 285 290 251]
 [ 45 134   5  72 183]
 [291 272 144 135 247]
 [ 86 235 151  12 113]
 [269 221  63 186  80]]
------
1 [[233  43 238 236  46]
 [202 166 129  24   4]
 [286 273 113  15  52]
 [ 80 244 274 179  54]
 [235 274 234  42  91]]
------


In [40]:
for index,value in np.ndenumerate(a):
    print(index,value)
    print("-----------")

(0, 0, 0) 136
-----------
(0, 0, 1) 204
-----------
(0, 0, 2) 285
-----------
(0, 0, 3) 290
-----------
(0, 0, 4) 251
-----------
(0, 1, 0) 45
-----------
(0, 1, 1) 134
-----------
(0, 1, 2) 5
-----------
(0, 1, 3) 72
-----------
(0, 1, 4) 183
-----------
(0, 2, 0) 291
-----------
(0, 2, 1) 272
-----------
(0, 2, 2) 144
-----------
(0, 2, 3) 135
-----------
(0, 2, 4) 247
-----------
(0, 3, 0) 86
-----------
(0, 3, 1) 235
-----------
(0, 3, 2) 151
-----------
(0, 3, 3) 12
-----------
(0, 3, 4) 113
-----------
(0, 4, 0) 269
-----------
(0, 4, 1) 221
-----------
(0, 4, 2) 63
-----------
(0, 4, 3) 186
-----------
(0, 4, 4) 80
-----------
(1, 0, 0) 233
-----------
(1, 0, 1) 43
-----------
(1, 0, 2) 238
-----------
(1, 0, 3) 236
-----------
(1, 0, 4) 46
-----------
(1, 1, 0) 202
-----------
(1, 1, 1) 166
-----------
(1, 1, 2) 129
-----------
(1, 1, 3) 24
-----------
(1, 1, 4) 4
-----------
(1, 2, 0) 286
-----------
(1, 2, 1) 273
-----------
(1, 2, 2) 113
-----------
(1, 2, 3) 15
-----------


In [41]:
for index,value in np.ndenumerate(a):
    print(value)

136
204
285
290
251
45
134
5
72
183
291
272
144
135
247
86
235
151
12
113
269
221
63
186
80
233
43
238
236
46
202
166
129
24
4
286
273
113
15
52
80
244
274
179
54
235
274
234
42
91


In [42]:
a = np.random.randint(1,1000,(3,3,3,3,3))

In [43]:
a

array([[[[[269, 499, 287],
          [210, 402, 145],
          [129, 672, 358]],

         [[202, 961, 757],
          [381, 423, 767],
          [535, 609, 835]],

         [[ 68, 447,  96],
          [356, 924,  83],
          [ 63, 759, 590]]],


        [[[507, 364,  49],
          [374, 990, 750],
          [460, 628, 471]],

         [[422, 780, 918],
          [930, 608, 684],
          [985, 737, 742]],

         [[ 74, 681, 358],
          [428, 748, 347],
          [584, 649, 726]]],


        [[[329, 413, 256],
          [878, 543, 124],
          [986, 666, 207]],

         [[466, 214, 959],
          [ 14, 682, 930],
          [517, 728, 351]],

         [[541, 552, 348],
          [104, 778, 264],
          [151,  33, 772]]]],



       [[[[522, 181, 973],
          [709, 159, 455],
          [377, 885, 331]],

         [[799, 138, 259],
          [962, 507, 999],
          [628, 491, 654]],

         [[460, 437, 646],
          [222, 341, 945],
          [959, 811, 675]

In [44]:
a.ndim

5

In [45]:
for index,value in np.ndenumerate(a):
    print(index,value)
    print("---------------------------------")

(0, 0, 0, 0, 0) 269
---------------------------------
(0, 0, 0, 0, 1) 499
---------------------------------
(0, 0, 0, 0, 2) 287
---------------------------------
(0, 0, 0, 1, 0) 210
---------------------------------
(0, 0, 0, 1, 1) 402
---------------------------------
(0, 0, 0, 1, 2) 145
---------------------------------
(0, 0, 0, 2, 0) 129
---------------------------------
(0, 0, 0, 2, 1) 672
---------------------------------
(0, 0, 0, 2, 2) 358
---------------------------------
(0, 0, 1, 0, 0) 202
---------------------------------
(0, 0, 1, 0, 1) 961
---------------------------------
(0, 0, 1, 0, 2) 757
---------------------------------
(0, 0, 1, 1, 0) 381
---------------------------------
(0, 0, 1, 1, 1) 423
---------------------------------
(0, 0, 1, 1, 2) 767
---------------------------------
(0, 0, 1, 2, 0) 535
---------------------------------
(0, 0, 1, 2, 1) 609
---------------------------------
(0, 0, 1, 2, 2) 835
---------------------------------
(0, 0, 2, 0, 0) 68
---------

In [46]:
a

array([[[[[269, 499, 287],
          [210, 402, 145],
          [129, 672, 358]],

         [[202, 961, 757],
          [381, 423, 767],
          [535, 609, 835]],

         [[ 68, 447,  96],
          [356, 924,  83],
          [ 63, 759, 590]]],


        [[[507, 364,  49],
          [374, 990, 750],
          [460, 628, 471]],

         [[422, 780, 918],
          [930, 608, 684],
          [985, 737, 742]],

         [[ 74, 681, 358],
          [428, 748, 347],
          [584, 649, 726]]],


        [[[329, 413, 256],
          [878, 543, 124],
          [986, 666, 207]],

         [[466, 214, 959],
          [ 14, 682, 930],
          [517, 728, 351]],

         [[541, 552, 348],
          [104, 778, 264],
          [151,  33, 772]]]],



       [[[[522, 181, 973],
          [709, 159, 455],
          [377, 885, 331]],

         [[799, 138, 259],
          [962, 507, 999],
          [628, 491, 654]],

         [[460, 437, 646],
          [222, 341, 945],
          [959, 811, 675]

In [47]:
a[0][0][0][1][1]

np.int32(402)

In [48]:
a[0][0][0][1][1] = 999888

In [49]:
a

array([[[[[   269,    499,    287],
          [   210, 999888,    145],
          [   129,    672,    358]],

         [[   202,    961,    757],
          [   381,    423,    767],
          [   535,    609,    835]],

         [[    68,    447,     96],
          [   356,    924,     83],
          [    63,    759,    590]]],


        [[[   507,    364,     49],
          [   374,    990,    750],
          [   460,    628,    471]],

         [[   422,    780,    918],
          [   930,    608,    684],
          [   985,    737,    742]],

         [[    74,    681,    358],
          [   428,    748,    347],
          [   584,    649,    726]]],


        [[[   329,    413,    256],
          [   878,    543,    124],
          [   986,    666,    207]],

         [[   466,    214,    959],
          [    14,    682,    930],
          [   517,    728,    351]],

         [[   541,    552,    348],
          [   104,    778,    264],
          [   151,     33,    772]]]],



  

In [50]:
a = np.random.randint(1,100,(3,3))

In [51]:
a

array([[64, 60,  3],
       [31, 18, 60],
       [71, 64, 87]], dtype=int32)

In [52]:
a[2][0]

np.int32(71)

In [53]:
a[-1][-1]

np.int32(87)

In [54]:
a[-1][-1] =  23

In [55]:
a

array([[64, 60,  3],
       [31, 18, 60],
       [71, 64, 23]], dtype=int32)

In [56]:
a[1]

array([31, 18, 60], dtype=int32)

In [57]:
a[2]

array([71, 64, 23], dtype=int32)

In [58]:
a = np.random.randint(1,100,(3,3,3))

In [59]:
a

array([[[30, 72, 93],
        [20,  1,  8],
        [94, 43, 88]],

       [[58, 81,  3],
        [35, 59, 77],
        [11, 80, 33]],

       [[70, 92, 17],
        [ 6, 64, 84],
        [76, 43, 39]]], dtype=int32)

In [60]:
a[0][0][-1]

np.int32(93)

In [61]:
a[1][2][-1]

np.int32(33)

In [62]:
a[1][2][-1] = 277

In [63]:
a

array([[[ 30,  72,  93],
        [ 20,   1,   8],
        [ 94,  43,  88]],

       [[ 58,  81,   3],
        [ 35,  59,  77],
        [ 11,  80, 277]],

       [[ 70,  92,  17],
        [  6,  64,  84],
        [ 76,  43,  39]]], dtype=int32)

In [64]:
# a[0][1][0]
# a [arr,row,col]

In [65]:
a

array([[[ 30,  72,  93],
        [ 20,   1,   8],
        [ 94,  43,  88]],

       [[ 58,  81,   3],
        [ 35,  59,  77],
        [ 11,  80, 277]],

       [[ 70,  92,  17],
        [  6,  64,  84],
        [ 76,  43,  39]]], dtype=int32)

In [66]:
a[0,1,0]

np.int32(20)

In [67]:
a[1,1,2]

np.int32(77)

In [68]:
a = np.random.randint(1,100,(2,2,3,3))

In [69]:
a

array([[[[58,  8, 89],
         [97, 39, 49],
         [28, 65, 50]],

        [[91, 10, 28],
         [53, 91, 58],
         [49, 24, 26]]],


       [[[20, 49, 98],
         [77, 76, 94],
         [31, 32, 29]],

        [[80, 85, 22],
         [85, 47, 47],
         [46, 95, 85]]]], dtype=int32)

In [70]:
# a[arr2,arr1,row,col]

In [71]:
a[1,1,0,-1]

np.int32(22)

In [72]:
a = np.random.randint(1,100,(5,5))

In [73]:
a

array([[21, 50, 34,  3, 98],
       [98, 99, 13, 83, 78],
       [67, 38, 32, 57, 82],
       [88, 82, 56, 98, 75],
       [16, 80, 81, 39, 56]], dtype=int32)

# Slicing
- a[row, cloumn]
- a[start:stop:step  , stat:stop:step]
- a[arr,row,col]
- a[start:stop:step, start:stop:step, start:stop,step]

In [74]:
a[1,1:4]

array([99, 13, 83], dtype=int32)

In [75]:
a[1:4,2]

array([13, 32, 56], dtype=int32)

In [76]:
a[1:4,2] = [0]*3

In [77]:
a

array([[21, 50, 34,  3, 98],
       [98, 99,  0, 83, 78],
       [67, 38,  0, 57, 82],
       [88, 82,  0, 98, 75],
       [16, 80, 81, 39, 56]], dtype=int32)

In [78]:
a[1:4,3:5]

array([[83, 78],
       [57, 82],
       [98, 75]], dtype=int32)

In [79]:
a[1:4,3:5] = 55

In [80]:
a

array([[21, 50, 34,  3, 98],
       [98, 99,  0, 55, 55],
       [67, 38,  0, 55, 55],
       [88, 82,  0, 55, 55],
       [16, 80, 81, 39, 56]], dtype=int32)

In [81]:
a[1:4,1:4]

array([[99,  0, 55],
       [38,  0, 55],
       [82,  0, 55]], dtype=int32)

In [82]:
a[1:4,1:4] = 0

In [83]:
a

array([[21, 50, 34,  3, 98],
       [98,  0,  0,  0, 55],
       [67,  0,  0,  0, 55],
       [88,  0,  0,  0, 55],
       [16, 80, 81, 39, 56]], dtype=int32)

In [84]:
a[::4]

array([[21, 50, 34,  3, 98],
       [16, 80, 81, 39, 56]], dtype=int32)

In [85]:
a = a.astype(str)

In [86]:
a[::4,::4]

array([['21', '98'],
       ['16', '56']], dtype='<U11')

In [87]:
a[::4,::4] = "Munna"

In [88]:
a

array([['Munna', '50', '34', '3', 'Munna'],
       ['98', '0', '0', '0', '55'],
       ['67', '0', '0', '0', '55'],
       ['88', '0', '0', '0', '55'],
       ['Munna', '80', '81', '39', 'Munna']], dtype='<U11')

In [89]:
a = np.random.randint(1,100,(3,3,3))

In [90]:
a

array([[[50, 91,  3],
        [71, 98,  6],
        [73, 30, 20]],

       [[26, 16, 55],
        [97, 83, 57],
        [42, 91, 27]],

       [[75,  9, 93],
        [33, 72, 88],
        [69, 87, 15]]], dtype=int32)

In [91]:
a[1::,0::,0::]

array([[[26, 16, 55],
        [97, 83, 57],
        [42, 91, 27]],

       [[75,  9, 93],
        [33, 72, 88],
        [69, 87, 15]]], dtype=int32)

In [92]:
a[1::2,0::,0::]

array([[[26, 16, 55],
        [97, 83, 57],
        [42, 91, 27]]], dtype=int32)

In [93]:
a[1::2,0::,0::] = 0

In [94]:
a

array([[[50, 91,  3],
        [71, 98,  6],
        [73, 30, 20]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[75,  9, 93],
        [33, 72, 88],
        [69, 87, 15]]], dtype=int32)

In [95]:
a[1]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [96]:
a[1,:,:]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [97]:
a[2,1:,1:]

array([[72, 88],
       [87, 15]], dtype=int32)

In [98]:
a[2,1:,1:]

array([[72, 88],
       [87, 15]], dtype=int32)

In [99]:
a[:,0,[0,2]]

array([[50,  3],
       [ 0,  0],
       [75, 93]], dtype=int32)

In [100]:
a[:,0,[0,2]] = 143

In [101]:
a

array([[[143,  91, 143],
        [ 71,  98,   6],
        [ 73,  30,  20]],

       [[143,   0, 143],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[143,   9, 143],
        [ 33,  72,  88],
        [ 69,  87,  15]]], dtype=int32)